[versions]
jackson = "2.20.0"
thymeleaf = "3.1.3.RELEASE"
mockitoCore = "5.14.2"
jimfs = "1.3.0"

[libraries]
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations" }

thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }